services:
  - type: web
    name: MerchantSite
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn MerchantSite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MerchantSite.settings
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        value: your-very-secret-key
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: merchantsite.onrender.com
      - key: EMAIL_USER
        value: your_gmail_address@gmail.com
      - key: EMAIL_PASS
        value: your_gmail_app_password
