# Generated by Django 5.2.3 on 2025-06-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('alcoholic', 'Alcoholic'), ('non_alcoholic', 'Non-Alcoholic'), ('water', 'Water'), ('beer', 'Beer'), ('juice', 'Juice'), ('carbonated', 'Carbonated'), ('kegs', 'Kegs')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
